name: Bun Install
description: Install dependencies with Bun

runs:
  using: 'composite'
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.4.0

    - name: Install dependencies
      shell: bash
      run: bun install
      env:
        CI: true
