/**
 * Provider contract types for tests.
 *
 * This file mirrors the specification in Issue #18 to provide compile-time
 * type checking for test suites.
 */

/**
 * Supported message delivery channels.
 */
export type Channel = 'whatsapp' | 'sms' | 'email';

/**
 * Delivery status for sent messages.
 */
export type DeliveryStatus = 'sent' | 'delivered' | 'read' | 'failed';

/**
 * Delivery status event reported by a provider webhook or status mechanism.
 */
export interface StatusEvent {
  /**
   * The vendor's message id.
   */
  providerId: string;
  /**
   * Current delivery status.
   */
  status: DeliveryStatus;
  /**
   * Optional error message describing delivery failure.
   */
  error?: string;
  /**
   * ISO timestamp of the status event.
   */
  at: string;
}

/**
 * Metadata associated with an outbound message dispatch.
 */
export interface OutboundMeta {
  /**
   * Recipient address or phone number.
   */
  to: string;
  /**
   * Unique message ID generated by the core.
   */
  messageId: string;
  /**
   * Template identifier used to render the message.
   */
  template: string;
  /**
   * Template kind: 'otp' or 'notification'.
   */
  kind: 'otp' | 'notification';
  /**
   * Message locale.
   */
  locale: string;
}

/**
 * Rendered payload for WhatsApp messages.
 */
export interface RenderedWhatsApp {
  /**
   * Approved Meta template configuration with name, language, and parameter values.
   */
  template?: {
    name: string;
    language: string;
    params: string[];
  };
  /**
   * Free-form text for 24-hour service window customer support messages.
   */
  text?: string;
}

/**
 * Rendered payload for SMS messages.
 */
export interface RenderedSms {
  /**
   * Rendered SMS text content.
   */
  text: string;
}

/**
 * Rendered payload for Email messages.
 */
export interface RenderedEmail {
  /**
   * Email subject line.
   */
  subject: string;
  /**
   * Plain text email body.
   */
  text: string;
  /**
   * Optional HTML email body.
   */
  html?: string;
}

/**
 * Result returned by a provider's send method.
 */
export type SendResult =
  | {
      /**
       * Indicates successful dispatch to the provider.
       */
      ok: true;
      /**
       * Vendor-assigned message ID.
       */
      providerId?: string;
    }
  | {
      /**
       * Indicates failure to dispatch to the provider.
       */
      ok: false;
      /**
       * Error description for the send failure.
       */
      error: string;
      /**
       * Whether the send attempt can be retried on the same channel.
       */
      retryable?: boolean;
    };

/**
 * Provider interface contract.
 *
 * A provider that does not define a `webhook` leaves delivery attempts
 * in the `sent` state until the fallback chain timeout elapses.
 */
export interface Provider<R = unknown> {
  /**
   * Unique provider identifier name (used in `/webhooks/:name` and status records).
   */
  name: string;
  /**
   * Delivery channel this provider operates on.
   */
  channel: Channel;
  /**
   * Send a rendered message along with outbound metadata.
   */
  send(message: R & OutboundMeta): Promise<SendResult>;
  /**
   * Optional webhook handlers for delivery status updates.
   */
  webhook?: {
    /**
     * Webhook verification handshake handler (e.g. GET challenge verification).
     * Returns null if the request is not a verification handshake.
     */
    verify?(request: Request): Promise<Response | null>;
    /**
     * Parse webhook delivery status payload into status events.
     * Throws an error to reject unsigned or invalid payloads.
     */
    parse(request: Request): Promise<StatusEvent[]>;
  };
}
