/**
 * Provider contract types and interfaces.
 *
 * A provider that does not define a `webhook` leaves delivery attempts
 * in the `sent` state until the fallback chain timeout elapses.
 *
 * @module
 */

/**
 * Every supported message delivery channel, in the canonical order.
 */
export const CHANNELS = ['whatsapp', 'sms', 'email'] as const;

/**
 * Supported message delivery channels.
 */
export type Channel = (typeof CHANNELS)[number];

/**
 * Message delivery status reported by providers or webhooks.
 */
export type DeliveryStatus = 'sent' | 'delivered' | 'read' | 'failed';

/**
 * Delivery status event reported by a provider webhook or status mechanism.
 */
export interface StatusEvent {
  /**
   * The vendor's message id.
   */
  providerId: string;
  /**
   * Current delivery status.
   */
  status: DeliveryStatus;
  /**
   * Optional error description if delivery failed.
   */
  error?: string;
  /**
   * ISO timestamp of when the status event occurred.
   */
  at: string;
}

/**
 * Outbound metadata associated with a message dispatch.
 */
export interface OutboundMeta {
  /**
   * Recipient address or phone number (e.g. E.164 phone or email address).
   */
  to: string;
  /**
   * Unique message ID generated by the core.
   */
  messageId: string;
  /**
   * What the message was rendered from.
   *
   * - For a free-text render (SMS, email, WhatsApp `text`) this is the catalogue template
   *   name, a `string`.
   * - For a WhatsApp Meta-template render it is the rendered template config
   *   (`{ name, language, params }`) instead, because the rendered payload and this meta share
   *   the `template` key and the provider cannot send without the config. In that case the
   *   catalogue name is not present anywhere in the payload; it remains on the `MessageRecord`.
   *
   * Interim shape; the contract-level fix is tracked in #28.
   */
  template: string | NonNullable<RenderedWhatsApp['template']>;
  /**
   * Template kind: 'otp' for sensitive one-time passwords, 'notification' for general alerts.
   */
  kind: 'otp' | 'notification';
  /**
   * Message locale (e.g. 'en', 'es').
   */
  locale: string;
}

/**
 * Rendered payload for WhatsApp messages.
 */
export interface RenderedWhatsApp {
  /**
   * Approved Meta template configuration with name, language, and parameter values.
   */
  template?: {
    name: string;
    language: string;
    params: string[];
  };
  /**
   * Free-form text for 24-hour service window customer support messages.
   */
  text?: string;
}

/**
 * Rendered payload for SMS messages.
 */
export interface RenderedSms {
  /**
   * Rendered SMS text body.
   */
  text: string;
}

/**
 * Rendered payload for Email messages.
 */
export interface RenderedEmail {
  /**
   * Email subject line.
   */
  subject: string;
  /**
   * Plain text email body.
   */
  text: string;
  /**
   * Optional HTML email body.
   */
  html?: string;
}

/**
 * Result returned by a provider's send method.
 */
export type SendResult =
  | {
      /**
       * Indicates successful dispatch to the provider.
       */
      ok: true;
      /**
       * Vendor-assigned message ID.
       */
      providerId?: string;
    }
  | {
      /**
       * Indicates failure to dispatch to the provider.
       */
      ok: false;
      /**
       * Error description for the send failure.
       */
      error: string;
      /**
       * Whether the send attempt can be retried on the same channel.
       */
      retryable?: boolean;
    };

/**
 * Options passed to a provider's webhook parse method.
 */
export interface WebhookParseOptions {
  /**
   * Whether the local-development bypass is in force for this request: the dispatcher sets it
   * only when `MESSAGING_DEV_UNSIGNED=true` and the request arrived on localhost. A provider
   * that honours it must skip signature verification and parse the body as-is.
   *
   * This is the one name for that flag. There are deliberately no aliases and no open index
   * signature: a provider that misspells it would silently keep enforcing signatures.
   */
  devUnsigned?: boolean;
}

/**
 * Provider interface contract.
 *
 * A provider without a `webhook` leaves attempts in the `sent` status
 * until the fallback chain timeout advances delivery.
 */
export interface Provider<R = unknown> {
  /**
   * Unique per configuration; used in /webhooks/:name and status records.
   */
  name: string;
  /**
   * Delivery channel this provider operates on.
   */
  channel: Channel;
  /**
   * Send a rendered message along with outbound metadata.
   */
  send(message: R & OutboundMeta): Promise<SendResult>;
  /**
   * Optional webhook handlers for delivery status updates.
   */
  webhook?: {
    /**
     * Handshake verification (e.g. GET challenge verification). Returns null if not a verification request.
     */
    verify?(request: Request): Promise<Response | null>;
    /**
     * Parse webhook delivery status payload into status events. Throws to reject unsigned/invalid payloads.
     */
    parse(request: Request, options?: WebhookParseOptions): Promise<StatusEvent[]>;
  };
  /**
   * Optional direct status lookup by message ID.
   */
  status?(messageId: string): Promise<unknown>;
  /**
   * Optional custom webhook/status request handler.
   */
  statusHandler?(request: Request): Promise<Response> | Response;
  /**
   * Optional internal hook for simulated status delivery.
   */
  onSimulatedStatus?(event: StatusEvent): void;
  /**
   * Optional legacy provider identifier.
   */
  id?: string;
}
