/**
 * Provider contract types and interfaces.
 *
 * A provider that does not define a `webhook` leaves delivery attempts
 * in the `sent` state until the fallback chain timeout elapses.
 *
 * @module
 */

/**
 * Supported message delivery channels.
 */
export type Channel = 'whatsapp' | 'sms' | 'email';

/**
 * Message delivery status reported by providers or webhooks.
 */
export type DeliveryStatus = 'sent' | 'delivered' | 'read' | 'failed';

/**
 * Delivery status event reported by a provider webhook or status mechanism.
 */
export interface StatusEvent {
  /**
   * The vendor's message id.
   */
  providerId: string;
  /**
   * Current delivery status.
   */
  status: DeliveryStatus;
  /**
   * Optional error description if delivery failed.
   */
  error?: string;
  /**
   * ISO timestamp of when the status event occurred.
   */
  at: string;
}

/**
 * Outbound metadata associated with a message dispatch.
 */
export interface OutboundMeta {
  /**
   * Recipient address or phone number (e.g. E.164 phone or email address).
   */
  to: string;
  /**
   * Unique message ID generated by the core.
   */
  messageId: string;
  /**
   * Template identifier used to render the message, or — see #28 — the rendered WhatsApp
   * template config when the payload carries one.
   */
  template: string | RenderedWhatsApp['template'];
  /**
   * Template kind: 'otp' for sensitive one-time passwords, 'notification' for general alerts.
   */
  kind: 'otp' | 'notification';
  /**
   * Message locale (e.g. 'en', 'es').
   */
  locale: string;
}

/**
 * Rendered payload for WhatsApp messages.
 */
export interface RenderedWhatsApp {
  /**
   * Approved Meta template configuration with name, language, and parameter values.
   */
  template?: {
    name: string;
    language: string;
    params: string[];
  };
  /**
   * Free-form text for 24-hour service window customer support messages.
   */
  text?: string;
}

/**
 * Rendered payload for SMS messages.
 */
export interface RenderedSms {
  /**
   * Rendered SMS text body.
   */
  text: string;
}

/**
 * Rendered payload for Email messages.
 */
export interface RenderedEmail {
  /**
   * Email subject line.
   */
  subject: string;
  /**
   * Plain text email body.
   */
  text: string;
  /**
   * Optional HTML email body.
   */
  html?: string;
}

/**
 * Result returned by a provider's send method.
 */
export type SendResult =
  | {
      /**
       * Indicates successful dispatch to the provider.
       */
      ok: true;
      /**
       * Vendor-assigned message ID.
       */
      providerId?: string;
    }
  | {
      /**
       * Indicates failure to dispatch to the provider.
       */
      ok: false;
      /**
       * Error description for the send failure.
       */
      error: string;
      /**
       * Whether the send attempt can be retried on the same channel.
       */
      retryable?: boolean;
    };

/**
 * Provider interface contract.
 *
 * A provider without a `webhook` leaves attempts in the `sent` status
 * until the fallback chain timeout advances delivery.
 */
export interface Provider<R = unknown> {
  /**
   * Unique per configuration; used in /webhooks/:name and status records.
   */
  name: string;
  /**
   * Delivery channel this provider operates on.
   */
  channel: Channel;
  /**
   * Send a rendered message along with outbound metadata.
   */
  send(message: R & OutboundMeta): Promise<SendResult>;
  /**
   * Optional webhook handlers for delivery status updates.
   */
  webhook?: {
    /**
     * Handshake verification (e.g. GET challenge verification). Returns null if not a verification request.
     */
    verify?(request: Request): Promise<Response | null>;
    /**
     * Parse webhook delivery status payload into status events. Throws to reject unsigned/invalid payloads.
     */
    parse(request: Request): Promise<StatusEvent[]>;
  };
  /**
   * Optional direct status lookup by message ID.
   */
  status?(messageId: string): Promise<unknown>;
  /**
   * Optional custom webhook/status request handler.
   */
  statusHandler?(request: Request): Promise<Response> | Response;
  /**
   * Optional internal hook for simulated status delivery.
   */
  onSimulatedStatus?(event: StatusEvent): void;
  /**
   * Optional legacy provider identifier.
   */
  id?: string;
}
